.TH "libstdf_const.h" 3 "13 Jul 2004" "libstdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libstdf_const.h \- 
.SH "Detailed Description"
.PP 
Constants for specific records/members. 


.PP
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMODE_AEL\fP   'A'"
.br
.ti -1c
.RI "#define \fBMODE_CHECKER\fP   'C'"
.br
.ti -1c
.RI "#define \fBMODE_DEBUG\fP   'D'"
.br
.ti -1c
.RI "#define \fBMODE_ENG\fP   'E'"
.br
.ti -1c
.RI "#define \fBMODE_MAINTENANCE\fP   'M'"
.br
.ti -1c
.RI "#define \fBMODE_PRODUCTION\fP   'P'"
.br
.ti -1c
.RI "#define \fBMODE_QUALITY\fP   'Q'"
.br
.ti -1c
.RI "#define \fBRETEST_YES\fP   'Y'"
.br
.ti -1c
.RI "#define \fBRETEST_NO\fP   'N'"
.br
.ti -1c
.RI "#define \fBRETEST_UNKNOWN\fP   ' '"
.br
.ti -1c
.RI "#define \fBBIN_PASS\fP   'P'"
.br
.ti -1c
.RI "#define \fBBIN_FAIL\fP   'F'"
.br
.ti -1c
.RI "#define \fBBIN_UNKNOWN\fP   ' '"
.br
.ti -1c
.RI "#define \fBPIN_GRP_UNKNOWN\fP   00"
.br
.ti -1c
.RI "#define \fBPIN_GRP_NORMAL\fP   10"
.br
.ti -1c
.RI "#define \fBPIN_GRP_SCIO\fP   20"
.br
.ti -1c
.RI "#define \fBPIN_GRP_SCIO_MID\fP   21"
.br
.ti -1c
.RI "#define \fBPIN_GRP_SCIO_VALID\fP   22"
.br
.ti -1c
.RI "#define \fBPIN_GRP_SCIO_SUS\fP   23"
.br
.ti -1c
.RI "#define \fBPIN_GRP_DUAL\fP   30"
.br
.ti -1c
.RI "#define \fBPIN_GRP_DUAL_MID\fP   31"
.br
.ti -1c
.RI "#define \fBPIN_GRP_DUAL_VALID\fP   32"
.br
.ti -1c
.RI "#define \fBPIN_GRP_DUAL_SUS\fP   33"
.br
.ti -1c
.RI "#define \fBRADIX_DEFAULT\fP   0"
.br
.ti -1c
.RI "#define \fBRADIX_BINARY\fP   2"
.br
.ti -1c
.RI "#define \fBRADIX_OCTAL\fP   8"
.br
.ti -1c
.RI "#define \fBRADIX_DECIMAL\fP   10"
.br
.ti -1c
.RI "#define \fBRADIX_HEX\fP   16"
.br
.ti -1c
.RI "#define \fBRADIX_SYMBOLIC\fP   20"
.br
.ti -1c
.RI "#define \fBUNIT_UNKNOWN\fP   0"
.br
.ti -1c
.RI "#define \fBUNIT_INCHES\fP   1"
.br
.ti -1c
.RI "#define \fBUNIT_CENTIMETERS\fP   2"
.br
.ti -1c
.RI "#define \fBUNIT_MILLIMETERS\fP   3"
.br
.ti -1c
.RI "#define \fBUNIT_MILS\fP   4"
.br
.ti -1c
.RI "#define \fBFLAT_UP\fP   'U'"
.br
.ti -1c
.RI "#define \fBFLAT_DOWN\fP   'D'"
.br
.ti -1c
.RI "#define \fBFLAT_LEFT\fP   'L'"
.br
.ti -1c
.RI "#define \fBFLAT_RIGHT\fP   'R'"
.br
.ti -1c
.RI "#define \fBFLAT_UNKNOWN\fP   ' '"
.br
.ti -1c
.RI "#define \fBPOS_LEFT\fP   'L'"
.br
.ti -1c
.RI "#define \fBPOS_RIGHT\fP   'R'"
.br
.ti -1c
.RI "#define \fBPOS_UNKNOWN\fP   ' '"
.br
.ti -1c
.RI "#define \fBPOS_UP\fP   'U'"
.br
.ti -1c
.RI "#define \fBPOS_DOWN\fP   'D'"
.br
.ti -1c
.RI "#define \fBPART_NEW_ID\fP   0x01"
.br
.ti -1c
.RI "#define \fBPART_NEW_COORD\fP   0x02"
.br
.ti -1c
.RI "#define \fBPART_TEST_ABORTED\fP   0x04"
.br
.ti -1c
.RI "#define \fBPART_FAILED\fP   0x08"
.br
.ti -1c
.RI "#define \fBPART_NO_INDICATION\fP   0x10"
.br
.ti -1c
.RI "#define \fBTEST_PARAMETRIC\fP   'P'"
.br
.ti -1c
.RI "#define \fBTEST_FUNCTIONAL\fP   'F'"
.br
.ti -1c
.RI "#define \fBTEST_MULTIPLE\fP   'M'"
.br
.ti -1c
.RI "#define \fBTEST_UNKNOWN\fP   ' '"
.br
.ti -1c
.RI "#define \fBTEST_MIN_INVALID\fP   0x01"
.br
.ti -1c
.RI "#define \fBTEST_MAX_INVALID\fP   0x02"
.br
.ti -1c
.RI "#define \fBTEST_TIM_INVALID\fP   0x04"
.br
.ti -1c
.RI "#define \fBTEST_SUMS_INVALID\fP   0x10"
.br
.ti -1c
.RI "#define \fBTEST_SQRS_INVALID\fP   0x20"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBcpu_types\fP { \fBCPU_TYPE_DEC\fP =  0, \fBCPU_TYPE_SPARC\fP =  1, \fBCPU_TYPE_X86\fP =  2, \fBCPU_TYPE_UNKNOWN\fP =  123 }"
.br
.ti -1c
.RI "enum \fBdtc_Vn_type\fP { \fBGDR_B0\fP =  0, \fBGDR_U1\fP =  1, \fBGDR_U2\fP =  2, \fBGDR_U4\fP =  3, \fBGDR_I1\fP =  4, \fBGDR_I2\fP =  5, \fBGDR_I4\fP =  6, \fBGDR_R4\fP =  7, \fBGDR_R8\fP =  8, \fBGDR_Cn\fP =  10, \fBGDR_Bn\fP =  11, \fBGDR_Dn\fP =  12, \fBGDR_N1\fP =  13 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBcpu_types\fP"
.PP
\fBEnumeration values: \fP
.in +1c
.TP
\fB\fICPU_TYPE_DEC \fP\fP
PDP-11 / VAX 
.TP
\fB\fICPU_TYPE_SPARC \fP\fP
sparc [Solaris] 
.TP
\fB\fICPU_TYPE_X86 \fP\fP
x86 [Sun386i / Windows / DOS] 
.TP
\fB\fICPU_TYPE_UNKNOWN \fP\fP
Unknown kind of CPU 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdf from the source code.
