.TH "libstdf_win32.h" 3 "13 Jul 2004" "libstdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libstdf_win32.h \- 
.SH "Detailed Description"
.PP 
Win32 specific definitions. 


.PP
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBfar\fP   _windows_is_a_pos_far"
.br
.ti -1c
.RI "#define \fBopen\fP   _open"
.br
.ti -1c
.RI "#define \fBLITTLE_ENDIAN\fP   1234"
.br
.ti -1c
.RI "#define \fBBIG_ENDIAN\fP   4321"
.br
.ti -1c
.RI "#define \fBBYTE_ORDER\fP   LITTLE_ENDIAN"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned __int8 \fBuint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned __int16 \fBuint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned __int32 \fBuint32_t\fP"
.br
.ti -1c
.RI "typedef unsigned __int64 \fBuint64_t\fP"
.br
.ti -1c
.RI "typedef signed __int8 \fBint8_t\fP"
.br
.ti -1c
.RI "typedef signed __int16 \fBint16_t\fP"
.br
.ti -1c
.RI "typedef signed __int32 \fBint32_t\fP"
.br
.ti -1c
.RI "typedef signed __int64 \fBint64_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdf from the source code.
